const STORAGE_KEY='healthLabData';
const THEME_KEY='healthLabTheme';
const $=id=>document.getElementById(id);
const clone=v=>JSON.parse(JSON.stringify(v));
const defaults={
 schemaVersion:4, profile:{name:'Luis'}, entries:[], events:[],
 trainingTypes:[
  {id:'run',name:'🏃 Carrera',enabled:true,order:1,kind:'run'},
  {id:'bike',name:'🚴 Bici / spinning',enabled:true,order:2,kind:'bike'},
  {id:'strength',name:'🏋️ Fuerza',enabled:true,order:3,kind:'strength'},
  {id:'mobility',name:'🧘 Movilidad / yoga',enabled:true,order:4,kind:'mobility'},
  {id:'trekking',name:'🥾 Trekking / senderismo',enabled:true,order:5,kind:'trekking'},
  {id:'other',name:'⚽ Otros',enabled:true,order:6,kind:'other'}
 ],
 dailySupplements:[
  {id:'multi',name:'Multivitamínico',dose:2,unit:'cápsulas',composition:'Vitaminas y minerales',enabled:true,order:1},
  {id:'omega3',name:'Omega-3',dose:1,unit:'cápsula',composition:'EPA/DHA',enabled:true,order:2},
  {id:'magnesium',name:'Magnesio',dose:1,unit:'cápsula',composition:'',enabled:true,order:3},
  {id:'coq10',name:'CoQ10',dose:1,unit:'cápsula',composition:'',enabled:true,order:4},
  {id:'vitd',name:'Vitamina D',dose:0,unit:'dosis',composition:'Hidroferol según pauta',enabled:true,order:5}
 ],
 sportSupplements:[
  {id:'protein',name:'Proteína',dose:25,unit:'g',composition:'Whey isolate',enabled:true,order:1},
  {id:'creatine',name:'Creatina',dose:5,unit:'g',composition:'Monohidrato',enabled:true,order:2},
  {id:'caffeine',name:'Cafeína',dose:0,unit:'mg',composition:'',enabled:true,order:3},
  {id:'carbsPre',name:'CH antes',dose:0,unit:'g',composition:'',enabled:true,order:4},
  {id:'carbsDuring',name:'CH durante',dose:0,unit:'g/h',composition:'',enabled:true,order:5},
  {id:'carbsPost',name:'CH después',dose:0,unit:'g',composition:'',enabled:true,order:6}
 ], medications:[]
};
function migrate(d){
 d=d||{}; d.entries=d.entries||[]; d.schemaVersion=4;
 d.trainingTypes=(d.trainingTypes||[]).some(x=>x.id==='run')?d.trainingTypes:clone(defaults.trainingTypes);
 d.dailySupplements=d.dailySupplements||clone(defaults.dailySupplements);
 d.sportSupplements=d.sportSupplements||clone(defaults.sportSupplements);
 d.medications=d.medications||d.medications||[];
 return {...clone(defaults),...d};
}
function loadData(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)return migrate(JSON.parse(raw));}catch{} return clone(defaults)}
let data=loadData(); function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))} saveData();
function localISO(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmtDate(d){return new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00'))}
function go(screen){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.go===screen));$(screen).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(screen==='record')prepareForm();if(screen==='calendar')renderCalendar();if(screen==='stats')renderStats();if(screen==='settings')renderSettings()}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('todayText').textContent=new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
function applyTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem(THEME_KEY,t)} applyTheme(localStorage.getItem(THEME_KEY)||'light'); $('themeToggle').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
function bindRanges(){document.querySelectorAll('input[type=range]').forEach(r=>{const o=r.parentElement.querySelector('output');const f=()=>{if(o)o.textContent=r.value};r.oninput=f;f()})} bindRanges();
$('usualSchedule').onchange=()=>$('sleepException').classList.toggle('hidden',$('usualSchedule').checked);
$('trainedYesterday').onchange=()=>$('trainingFields').classList.toggle('hidden',!$('trainedYesterday').checked);
$('trainingType').onchange=renderTrainingFields;
function prepareForm(){
 $('entryDate').value=$('entryDate').value||localISO();
 $('trainingType').innerHTML=data.trainingTypes.filter(x=>x.enabled!==false).sort((a,b)=>(a.order||0)-(b.order||0)).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');
 renderTrainingFields(); renderSupplementInputs();
}
function renderTrainingFields(){
 const t=data.trainingTypes.find(x=>x.id===$('trainingType').value)||data.trainingTypes[0]; if(!t){$('trainingDynamic').innerHTML='';return}
 const common=`<div class="grid two"><label>RPE global<input id="rpeGlobal" type="number" min="0" max="10" value="0"></label><label>RPE piernas<input id="rpeLegs" type="number" min="0" max="10" value="0"></label><label>RPE cardio<input id="rpeCardio" type="number" min="0" max="10" value="0"></label></div>`;
 const load=`<div class="grid three"><label>Carga<input id="tssValue" type="number" min="0" step="0.1"></label><label>Tipo de TSS<select id="tssType"><option selected>hrTSS</option><option>TSS</option><option>rTSS</option><option>Otro</option></select></label><label>IF<input id="ifValue" type="number" min="0" max="2" step="0.01"></label></div>`;
 let html='';
 if(t.kind==='run')html=`<div class="grid two"><label>Terreno<select id="terrain"><option>Asfalto</option><option>Pista</option><option>Camino</option><option>Montaña</option><option>Mixto</option></select></label><label>Kilómetros<input id="distanceKm" type="number" min="0" step="0.01"></label><label>Desnivel + (m)<input id="elevGain" type="number" min="0"></label><label>Desnivel − (m)<input id="elevLoss" type="number" min="0"></label><label>Ritmo medio (min/km)<input id="avgPace" type="text" placeholder="Ej. 5:42"></label></div>${load}${common}`;
 else if(t.kind==='bike')html=`<div class="grid two"><label>Distancia (km, opcional)<input id="distanceKm" type="number" min="0" step="0.01"></label><label>Potencia media (W)<input id="avgPower" type="number" min="0"></label><label>Cadencia media<input id="avgCadence" type="number" min="0"></label></div>${load}${common}`;
 else if(t.kind==='trekking')html=`<div class="grid two"><label>Kilómetros<input id="distanceKm" type="number" min="0" step="0.01"></label><label>Desnivel + (m)<input id="elevGain" type="number" min="0"></label><label>Desnivel − (m)<input id="elevLoss" type="number" min="0"></label></div>${common}`;
 else if(t.kind==='strength')html=common;
 else if(t.kind==='mobility')html='';
 else html=`<div class="grid two"><label>RPE global<input id="rpeGlobal" type="number" min="0" max="10" value="0"></label></div>`;
 $('trainingDynamic').innerHTML=html;
}
function renderSupplementInputs(){
 const render=(arr,id)=>{$(id).innerHTML=arr.filter(x=>x.enabled!==false).sort((a,b)=>(a.order||0)-(b.order||0)).map(x=>`<div class="supp-entry"><label class="switch-row"><input type="checkbox" data-supp-check="${x.id}" data-group="${id}"><span><strong>${esc(x.name)}</strong><small>${esc(x.composition||'')}</small></span></label><div class="supp-dose"><input type="number" min="0" step="0.1" value="${x.dose??0}" data-supp-dose="${x.id}" data-group="${id}"><span>${esc(x.unit||'')}</span></div></div>`).join('')||'<div class="empty-config">Sin elementos configurados.</div>'};
 render(data.dailySupplements,'dailySupplements');render(data.sportSupplements,'sportSupplements');
}
function getNum(id){return $(id)?Number($(id).value||0):0} function getVal(id){return $(id)?$(id).value:''}
function collectSupp(group){const arr=group==='dailySupplements'?data.dailySupplements:data.sportSupplements;return arr.filter(x=>document.querySelector(`[data-supp-check="${x.id}"][data-group="${group}"]`)?.checked).map(x=>({id:x.id,name:x.name,amount:Number(document.querySelector(`[data-supp-dose="${x.id}"][data-group="${group}"]`)?.value||0),unit:x.unit,composition:x.composition||''}))}
$('quickForm').onsubmit=e=>{e.preventDefault();const date=$('entryDate').value||localISO();const trained=$('trainedYesterday').checked;const tt=data.trainingTypes.find(x=>x.id===$('trainingType').value);const entry={id:Date.now(),date,fatigue:getNum('fatigue'),legFatigue:getNum('legFatigue'),handSwelling:getNum('handSwelling'),handPain:getNum('handPain'),handStiffness:getNum('handStiffness'),peeling:getNum('peeling'),sleepQuality:getNum('sleepQuality'),sleepHours:getNum('sleepHours'),usualSchedule:$('usualSchedule').checked,sleepNotes:$('usualSchedule').checked?'':getVal('sleepNotes').trim(),trainedYesterday:trained,training:trained?{typeId:tt?.id||'',typeName:tt?.name||'',kind:tt?.kind||'',competition:$('competition').checked,durationSeconds:getNum('durationHours')*3600+getNum('durationMinutes')*60+getNum('durationSeconds'),terrain:getVal('terrain'),distanceKm:getNum('distanceKm'),elevGain:getNum('elevGain'),elevLoss:getNum('elevLoss'),avgPace:getVal('avgPace'),tssValue:getNum('tssValue'),tssType:getVal('tssType')||'hrTSS',ifValue:getNum('ifValue'),avgPower:getNum('avgPower'),avgCadence:getNum('avgCadence'),rpeGlobal:getNum('rpeGlobal'),rpeLegs:getNum('rpeLegs'),rpeCardio:getNum('rpeCardio'),notes:getVal('trainingNotes').trim()}:null,dailySupplements:collectSupp('dailySupplements'),sportSupplements:collectSupp('sportSupplements'),notes:getVal('notes').trim()};const idx=data.entries.findIndex(x=>x.date===date);if(idx>=0){if(!confirm('Ya hay un registro para esa fecha. ¿Sustituirlo?'))return;entry.id=data.entries[idx].id;data.entries.splice(idx,1)}data.entries.push(entry);data.entries.sort((a,b)=>a.date.localeCompare(b.date));saveData();alert('Registro guardado.');resetForm();go('home');updateHome()};
function resetForm(){$('quickForm').reset();document.querySelectorAll('input[type=range]').forEach(r=>{r.value=0;r.dispatchEvent(new Event('input'))});$('usualSchedule').checked=true;$('sleepException').classList.add('hidden');$('trainingFields').classList.add('hidden');$('entryDate').value=localISO();prepareForm()}
function updateHome(){const e=data.entries.find(x=>x.date===localISO());const cards=document.querySelectorAll('.metric-card strong');if(cards[0])cards[0].textContent=e?e.handSwelling:0;if(cards[1])cards[1].textContent=e?e.fatigue:0;const pill=document.querySelector('.hero-card .pill');if(pill)pill.textContent=e?'Registro completado':'Registro pendiente'} updateHome();
let calendarDate=new Date(); $('prevMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()}; $('nextMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$('calendarTitle').textContent=new Intl.DateTimeFormat('es-ES',{month:'long',year:'numeric'}).format(calendarDate);const first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7,c=[];for(let i=0;i<start;i++)c.push('<div class="day empty"></div>');for(let d=1;d<=last.getDate();d++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,e=data.entries.find(x=>x.date===iso);let sev=0;if(e){const mx=Math.max(e.handSwelling||0,e.handPain||0,e.handStiffness||0,e.fatigue||0,e.legFatigue||0);sev=mx>=7?3:mx>=4?2:1}c.push(`<button class="day ${e?'has-entry severity-'+sev:''}${iso===localISO()?' today':''}" data-date="${iso}">${d}${e?'<span class="day-dot"></span>':''}</button>`)}$('calendarGrid').innerHTML=c.join('');document.querySelectorAll('.day[data-date]').forEach(b=>b.onclick=()=>showDay(b.dataset.date))}
function durationText(s=0){const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return [h?`${h} h`:'',m?`${m} min`:'',sec?`${sec} s`:''].filter(Boolean).join(' ')||'0 min'}
function showDay(date){const e=data.entries.find(x=>x.date===date);if(!e){$('dayDetail').innerHTML=`<div class="day-detail-card"><strong>${fmtDate(date)}</strong><p class="muted">Sin registro.</p></div>`;return}const t=e.training;const supp=[...(e.dailySupplements||[]),...(e.sportSupplements||[])];$('dayDetail').innerHTML=`<div class="day-detail-card"><strong>${fmtDate(date)}</strong><div class="detail-grid"><p><b>😴 Sueño:</b> ${e.sleepQuality??0}/100 · ${e.sleepHours??0} h${e.usualSchedule===false?' · horario no habitual':''}</p><p><b>🤲 Salud:</b> inflamación ${e.handSwelling}/10 · dolor ${e.handPain}/10 · rigidez ${e.handStiffness}/10 · descamación ${e.peeling}/3</p><p><b>⚡ Estado:</b> cansancio ${e.fatigue}/10 · piernas ${e.legFatigue}/10</p>${t?`<div class="training-summary"><b>${esc(t.typeName||'Entrenamiento')}${t.competition?' · 🏁 Competición':''}</b><span>${durationText(t.durationSeconds)}${t.distanceKm?` · ${t.distanceKm} km`:''}${t.elevGain?` · +${t.elevGain} m`:''}${t.elevLoss?` · −${t.elevLoss} m`:''}${t.tssValue?` · ${t.tssValue} ${esc(t.tssType)}`:''}${t.ifValue?` · IF ${t.ifValue}`:''}</span><span>RPE global ${t.rpeGlobal||0} · piernas ${t.rpeLegs||0} · cardio ${t.rpeCardio||0}</span>${t.notes?`<p>${esc(t.notes)}</p>`:''}</div>`:''}${supp.length?`<p><b>💊 Tomado:</b> ${supp.map(s=>`${esc(s.name)} ${s.amount} ${esc(s.unit)}`).join(' · ')}</p>`:''}${e.sleepNotes?`<p><b>Sueño:</b> ${esc(e.sleepNotes)}</p>`:''}${e.notes?`<p><b>Observaciones:</b> ${esc(e.notes)}</p>`:''}</div><button class="danger" onclick="deleteEntry('${date}')">Eliminar</button></div>`}
window.deleteEntry=date=>{if(confirm('¿Eliminar este registro?')){data.entries=data.entries.filter(x=>x.date!==date);saveData();renderCalendar();$('dayDetail').innerHTML='';updateHome()}};
function renderStats(){const arr=[...data.entries].sort((a,b)=>a.date.localeCompare(b.date));const avg=k=>arr.length?(arr.reduce((s,e)=>s+Number(e[k]||0),0)/arr.length).toFixed(1):'—';$('statsCards').innerHTML=[['Días registrados',arr.length],['Inflamación media',avg('handSwelling')],['Cansancio medio',avg('fatigue')],['Entrenamientos',arr.filter(e=>e.training).length]].map(([l,v])=>`<article class="stat-card"><span>${l}</span><strong>${v}</strong></article>`).join('');drawChart(arr)}
function drawChart(arr){const c=$('statsChart'),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth||700,h=220;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#dfe8e8';for(let i=0;i<=5;i++){const y=20+i*(h-40)/5;ctx.beginPath();ctx.moveTo(28,y);ctx.lineTo(w-8,y);ctx.stroke()}if(!arr.length){ctx.fillStyle='#74868b';ctx.fillText('Sin datos',w/2-20,h/2);return}for(const [k,col] of [['handSwelling','#0f766e'],['fatigue','#d99a24']]){ctx.strokeStyle=col;ctx.lineWidth=3;ctx.beginPath();arr.forEach((e,i)=>{const x=30+i*(w-44)/Math.max(1,arr.length-1),y=h-20-(Number(e[k]||0)/10)*(h-40);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}}
const configMeta={dailySupplements:{title:'Suplemento diario',fields:true},sportSupplements:{title:'Suplemento deportivo',fields:true},medications:{title:'Medicación',fields:true},trainingTypes:{title:'Tipo de entrenamiento',fields:false}};
function renderSettings(){for(const key of ['dailySupplements','sportSupplements','medications','trainingTypes']){const list=$(key+'List'),arr=data[key]||[];list.innerHTML=arr.sort((a,b)=>(a.order||0)-(b.order||0)).map((x,i)=>`<div class="config-item"><span class="config-grip">⋮⋮</span><div class="config-main"><strong>${esc(x.name)}</strong><small>${key==='trainingTypes'?esc(x.kind||'otro'):`${x.dose??0} ${esc(x.unit||'')} ${x.composition?`· ${esc(x.composition)}`:''}`}</small></div><button class="config-toggle ${x.enabled!==false?'on':''}" data-toggle="${key}" data-id="${x.id}"></button><button class="icon-mini" data-edit="${key}" data-id="${x.id}">✎</button><button class="icon-mini danger-text" data-del="${key}" data-id="${x.id}">×</button></div>`).join('')||'<div class="empty-config">Sin elementos.</div>'}bindConfigButtons()}
function bindConfigButtons(){document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const x=data[b.dataset.toggle].find(v=>v.id===b.dataset.id);x.enabled=!x.enabled;saveData();renderSettings()});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openConfigModal(b.dataset.edit,b.dataset.id));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar este elemento?')){data[b.dataset.del]=data[b.dataset.del].filter(x=>x.id!==b.dataset.id);saveData();renderSettings()}})}
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openConfigModal(b.dataset.add));let modalState=null;
function openConfigModal(key,id=''){const item=id?data[key].find(x=>x.id===id):null;modalState={key,id};$('modalTitle').textContent=(item?'Editar ':'Añadir ')+(configMeta[key]?.title||'elemento');const isTrain=key==='trainingTypes';$('modalBody').innerHTML=`<label>Nombre<input id="cfgName" value="${esc(item?.name||'')}"></label>${isTrain?`<label>Tipo de formulario<select id="cfgKind"><option value="run">Carrera</option><option value="bike">Bici</option><option value="strength">Fuerza</option><option value="mobility">Movilidad</option><option value="trekking">Trekking</option><option value="other">Otros</option></select></label>`:`<div class="grid two"><label>Dosis habitual<input id="cfgDose" type="number" step="0.1" value="${item?.dose??0}"></label><label>Unidad<input id="cfgUnit" value="${esc(item?.unit||'')}"></label></div><label>Composición / detalle<textarea id="cfgComposition" rows="3">${esc(item?.composition||'')}</textarea></label>`}`;$('modalBackdrop').classList.add('open');if(isTrain&&item)$('cfgKind').value=item.kind||'other'}
$('modalCancel').onclick=()=>$('modalBackdrop').classList.remove('open');$('modalSave').onclick=()=>{const {key,id}=modalState,name=$('cfgName').value.trim();if(!name)return alert('Escribe un nombre.');let item=id?data[key].find(x=>x.id===id):null;if(!item){item={id:`${key}-${Date.now()}`,enabled:true,order:data[key].length+1};data[key].push(item)}item.name=name;if(key==='trainingTypes')item.kind=$('cfgKind').value;else{item.dose=Number($('cfgDose').value||0);item.unit=$('cfgUnit').value.trim();item.composition=$('cfgComposition').value.trim()}saveData();$('modalBackdrop').classList.remove('open');renderSettings()};
$('exportAll').onclick=()=>download(JSON.stringify(data,null,2),`healthlab_backup_${localISO()}.json`,'application/json');
$('exportCsv').onclick=()=>{const rows=[['date','sleepQuality','sleepHours','fatigue','legFatigue','handSwelling','handPain','handStiffness','peeling','trainingType','durationSeconds','distanceKm','elevGain','elevLoss','tssValue','tssType','ifValue','rpeGlobal','rpeLegs','rpeCardio','trainingNotes','notes']];for(const e of data.entries){const t=e.training||{};rows.push([e.date,e.sleepQuality,e.sleepHours,e.fatigue,e.legFatigue,e.handSwelling,e.handPain,e.handStiffness,e.peeling,t.typeName,t.durationSeconds,t.distanceKm,t.elevGain,t.elevLoss,t.tssValue,t.tssType,t.ifValue,t.rpeGlobal,t.rpeLegs,t.rpeCardio,t.notes,e.notes])}const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');download(csv,`healthlab_${localISO()}.csv`,'text/csv;charset=utf-8')};
function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('importAll').onchange=async e=>{try{const obj=JSON.parse(await e.target.files[0].text());if(!obj||!Array.isArray(obj.entries))throw 0;if(confirm('Esto sustituirá todos los datos actuales. ¿Continuar?')){data=migrate(obj);saveData();alert('Datos importados.');renderSettings();updateHome()}}catch{alert('Archivo JSON no válido.')}};
$('resetDemo').onclick=()=>{if(confirm('¿Restablecer toda la aplicación?')){data=clone(defaults);saveData();location.reload()}};
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js?v=1.0.1');prepareForm();renderSettings();
