const STORAGE_KEY='healthLabData';
const THEME_KEY='healthLabTheme';
const $=id=>document.getElementById(id);
const clone=v=>JSON.parse(JSON.stringify(v));
const defaults={
 schemaVersion:6,profile:{name:'Luis'},entries:[],events:[],
 trainingTypes:[
  {id:'run',name:'🏃 Carrera',enabled:true,order:1,kind:'run'},
  {id:'bike',name:'🚴 Bici / spinning',enabled:true,order:2,kind:'bike'},
  {id:'strength',name:'🏋️ Fuerza',enabled:true,order:3,kind:'strength'},
  {id:'mobility',name:'🧘 Movilidad / yoga',enabled:true,order:4,kind:'mobility'},
  {id:'trekking',name:'🥾 Trekking / senderismo',enabled:true,order:5,kind:'trekking'},
  {id:'other',name:'⚽ Otros',enabled:true,order:6,kind:'other'}],
 dailySupplements:[
  {id:'multi',name:'Multivitamínico',dose:2,unit:'cápsulas',composition:'Vitaminas y minerales',enabled:true,order:1,defaultTaken:true},
  {id:'omega3',name:'Omega-3',dose:1,unit:'cápsula',composition:'EPA/DHA',enabled:true,order:2,defaultTaken:true},
  {id:'magnesium',name:'Magnesio',dose:1,unit:'cápsula',composition:'',enabled:true,order:3,defaultTaken:true},
  {id:'coq10',name:'CoQ10',dose:1,unit:'cápsula',composition:'Incluida en el multivitamínico',enabled:false,order:4,defaultTaken:false},
  {id:'vitd',name:'Vitamina D / Hidroferol',dose:1,unit:'dosis',composition:'Según pauta mensual',enabled:true,order:5,defaultTaken:false}],
 sportSupplements:[
  {id:'protein',name:'Proteína',dose:25,unit:'g',composition:'Whey isolate',enabled:true,order:1,defaultTaken:true},
  {id:'creatine',name:'Creatina',dose:5,unit:'g',composition:'Monohidrato',enabled:true,order:2,defaultTaken:false},
  {id:'caffeine',name:'Cafeína',dose:0,unit:'mg',composition:'',enabled:true,order:3,defaultTaken:false},
  {id:'carbsPre',name:'CH antes',dose:0,unit:'g',composition:'',enabled:true,order:4,defaultTaken:false},
  {id:'carbsDuring',name:'CH durante',dose:0,unit:'g/h',composition:'',enabled:true,order:5,defaultTaken:false},
  {id:'carbsPost',name:'CH después',dose:0,unit:'g',composition:'',enabled:true,order:6,defaultTaken:false}],
 medications:[]
};
function migrate(d){
 d=d||{};d.entries=Array.isArray(d.entries)?d.entries:[];d.events=Array.isArray(d.events)?d.events:[];d.schemaVersion=6;
 d.trainingTypes=Array.isArray(d.trainingTypes)&&d.trainingTypes.length?d.trainingTypes:clone(defaults.trainingTypes);
 d.dailySupplements=Array.isArray(d.dailySupplements)&&d.dailySupplements.length?d.dailySupplements:clone(defaults.dailySupplements);
 d.sportSupplements=Array.isArray(d.sportSupplements)&&d.sportSupplements.length?d.sportSupplements:clone(defaults.sportSupplements);
 d.medications=Array.isArray(d.medications)?d.medications:[];
 for(const x of d.dailySupplements){
  if(x.defaultTaken===undefined)x.defaultTaken=['multi','omega3','magnesium'].includes(x.id);
  if(x.id==='coq10')x.enabled=false;
 }
 for(const x of d.sportSupplements)if(x.defaultTaken===undefined)x.defaultTaken=x.id==='protein';
 for(const e of d.entries){
  if(!Array.isArray(e.trainings)){e.trainings=e.training?[e.training]:[];delete e.training}
  if(!e.sleepDuration&&e.sleepHours!==undefined){const mins=Math.round(Number(e.sleepHours||0)*60);e.sleepDuration=minutesText(mins)}
  e.legFatigue=Boolean(e.legFatigue);
  e.eyeTic=Boolean(e.eyeTic);
  for(const t of e.trainings){
   const parsed=parseDuration(t.duration||'');
   if(parsed!==null){t.durationMinutes=parsed;t.duration=minutesText(parsed)}
   else if(Number(t.durationSeconds)>86400&&Number(t.durationSeconds)<216000){const mins=Math.floor(Number(t.durationSeconds)/3600);t.durationMinutes=mins;t.duration=minutesText(mins)}
   else if(Number.isFinite(Number(t.durationMinutes))&&Number(t.durationMinutes)>0){let mins=Number(t.durationMinutes);if(mins>1440&&mins%60===0)mins=Math.round(mins/60);t.durationMinutes=mins;t.duration=minutesText(mins)}
   delete t.durationSeconds;
  }
  delete e.handStiffness;
 }
 delete d.supplements;delete d.symptoms;delete d.appVersion;
 return {...clone(defaults),...d,schemaVersion:6};
}
function loadData(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)return migrate(JSON.parse(raw))}catch{}return clone(defaults)}
let data=loadData();function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}saveData();
function localISO(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmtDate(d){return new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00'))}
function parseDuration(v){v=String(v||'').trim().replace(',', '.');if(!v)return 0;if(/^\d+$/.test(v))return Number(v);if(!/^\d{1,3}:\d{1,2}$/.test(v))return null;const [h,m]=v.split(':').map(Number);if(m>59)return null;return h*60+m}
function minutesText(m=0){return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
function go(screen){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.go===screen));$(screen).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(screen==='record')prepareNewRecord();if(screen==='calendar')renderCalendar();if(screen==='stats')renderStats();if(screen==='settings')renderSettings()}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('todayText').textContent=new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
function applyTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem(THEME_KEY,t)}applyTheme(localStorage.getItem(THEME_KEY)||'light');$('themeToggle').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
function bindRanges(root=document){root.querySelectorAll('input[type=range]').forEach(r=>{const o=r.closest('.scale-control')?.querySelector('output');const f=()=>{if(o)o.textContent=r.value};r.oninput=f;f()})}bindRanges();
$('usualSchedule').onchange=()=>$('sleepException').classList.toggle('hidden',$('usualSchedule').checked);
$('usualFood').onchange=()=>$('foodException').classList.toggle('hidden',$('usualFood').checked);
let trainingDrafts=[];
function enabledTrainingTypes(){return data.trainingTypes.filter(x=>x.enabled!==false).sort((a,b)=>(a.order||0)-(b.order||0))}
function newTraining(){const t=enabledTrainingTypes()[0]||{id:'other',name:'⚽ Otros',kind:'other'};return {uid:`tr-${Date.now()}-${Math.random()}`,typeId:t.id,typeName:t.name,kind:t.kind,competition:false,duration:'',temperature:'',notes:'',terrain:'Camino',distanceKm:'',elevGain:'',elevLoss:'',avgPace:'',tssValue:'',tssType:'hrTSS',ifValue:'',avgPower:'',avgCadence:'',rpeGlobal:0,rpeLegs:0,rpeCardio:0}}
$('addTraining').onclick=()=>{syncTrainingDrafts();trainingDrafts.push(newTraining());renderTrainingList()};
function syncTrainingDrafts(){document.querySelectorAll('.training-card').forEach(card=>{const i=Number(card.dataset.index),d=trainingDrafts[i];if(!d)return;card.querySelectorAll('[data-field]').forEach(el=>{d[el.dataset.field]=el.type==='checkbox'?el.checked:el.value});const tt=data.trainingTypes.find(x=>x.id===d.typeId);if(tt){d.typeName=tt.name;d.kind=tt.kind}})}
function typeOptions(selected){return enabledTrainingTypes().map(x=>`<option value="${esc(x.id)}" ${x.id===selected?'selected':''}>${esc(x.name)}</option>`).join('')}
function rangeField(label,field,val=0){return `<label class="scale-card mini-scale"><span>${label}</span><div class="scale-control"><input type="range" min="0" max="10" value="${Number(val)||0}" data-field="${field}"><output>${Number(val)||0}</output></div></label>`}
function dynamicFields(d){const load=`<div class="grid three"><label>Carga<input data-field="tssValue" type="number" min="0" step="0.1" value="${esc(d.tssValue)}"></label><label>Tipo TSS<select data-field="tssType"><option ${d.tssType==='hrTSS'?'selected':''}>hrTSS</option><option ${d.tssType==='TSS'?'selected':''}>TSS</option><option ${d.tssType==='rTSS'?'selected':''}>rTSS</option><option ${d.tssType==='Otro'?'selected':''}>Otro</option></select></label><label>IF<input data-field="ifValue" type="number" min="0" max="2" step="0.01" value="${esc(d.ifValue)}"></label></div>`;
 const rpes=`<div class="metric-form-grid training-rpes">${rangeField('RPE global','rpeGlobal',d.rpeGlobal)}${rangeField('RPE piernas','rpeLegs',d.rpeLegs)}${rangeField('RPE cardio','rpeCardio',d.rpeCardio)}</div>`;
 if(d.kind==='run')return `<div class="grid two"><label>Terreno<select data-field="terrain">${['Asfalto','Pista','Camino','Montaña','Mixto'].map(x=>`<option ${d.terrain===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Kilómetros<input data-field="distanceKm" type="number" min="0" step="0.01" value="${esc(d.distanceKm)}"></label><label>Desnivel + (m)<input data-field="elevGain" type="number" min="0" value="${esc(d.elevGain)}"></label><label>Desnivel − (m)<input data-field="elevLoss" type="number" min="0" value="${esc(d.elevLoss)}"></label><label>Ritmo medio<input data-field="avgPace" placeholder="Ej. 5:42" value="${esc(d.avgPace)}"></label></div>${load}${rpes}`;
 if(d.kind==='bike')return `<div class="grid two"><label>Distancia (km)<input data-field="distanceKm" type="number" min="0" step="0.01" value="${esc(d.distanceKm)}"></label><label>Potencia media (W)<input data-field="avgPower" type="number" min="0" value="${esc(d.avgPower)}"></label><label>Cadencia media<input data-field="avgCadence" type="number" min="0" value="${esc(d.avgCadence)}"></label></div>${load}${rpes}`;
 if(d.kind==='trekking')return `<div class="grid two"><label>Kilómetros<input data-field="distanceKm" type="number" min="0" step="0.01" value="${esc(d.distanceKm)}"></label><label>Desnivel + (m)<input data-field="elevGain" type="number" min="0" value="${esc(d.elevGain)}"></label><label>Desnivel − (m)<input data-field="elevLoss" type="number" min="0" value="${esc(d.elevLoss)}"></label></div>${rpes}`;
 if(d.kind==='strength')return rpes;
 if(d.kind==='mobility')return '';
 return `<div class="metric-form-grid training-rpes">${rangeField('RPE global','rpeGlobal',d.rpeGlobal)}</div>`;
}
function renderTrainingList(){const list=$('trainingList');if(!trainingDrafts.length){list.innerHTML='<div class="empty-config">Sin entrenamiento registrado.</div>';return}list.innerHTML=trainingDrafts.map((d,i)=>`<div class="training-card" data-index="${i}"><div class="training-card-head"><strong>Entrenamiento ${i+1}</strong><button type="button" class="icon-mini danger-text" data-remove-training="${i}">Eliminar</button></div><div class="grid two"><label>Tipo<select data-field="typeId">${typeOptions(d.typeId)}</select></label><label>Duración (minutos o h:mm)<input data-field="duration" inputmode="numeric" maxlength="6" placeholder="Ej. 42 o 1:20" value="${esc(d.duration)}"></label></div><div class="inline-options"><label class="tick-card small-tick"><input type="checkbox" data-field="competition" ${d.competition?'checked':''}><span>🏁 Competición</span></label><label>Temperatura<select data-field="temperature"><option value="">Sin registrar</option><option ${d.temperature==='Frío'?'selected':''}>Frío</option><option ${d.temperature==='Templado'?'selected':''}>Templado</option><option ${d.temperature==='Calor'?'selected':''}>Calor</option><option ${d.temperature==='Calor intenso'?'selected':''}>Calor intenso</option></select></label></div><div class="training-dynamic">${dynamicFields(d)}</div><label>Comentario<textarea data-field="notes" rows="3" placeholder="Sensaciones, dolor, explicación del RPE...">${esc(d.notes)}</textarea></label></div>`).join('');bindRanges(list);list.querySelectorAll('[data-remove-training]').forEach(b=>b.onclick=()=>{syncTrainingDrafts();trainingDrafts.splice(Number(b.dataset.removeTraining),1);renderTrainingList()});list.querySelectorAll('[data-field="typeId"]').forEach(s=>s.onchange=()=>{syncTrainingDrafts();const d=trainingDrafts[Number(s.closest('.training-card').dataset.index)],tt=data.trainingTypes.find(x=>x.id===d.typeId);if(tt){d.typeName=tt.name;d.kind=tt.kind}renderTrainingList()})}
function renderItemInputs(arr,id){$(id).innerHTML=arr.filter(x=>x.enabled!==false).sort((a,b)=>(a.order||0)-(b.order||0)).map(x=>`<div class="supp-entry"><label class="switch-row"><input type="checkbox" data-item-check="${x.id}" data-group="${id}" ${x.defaultTaken?'checked':''}><span><strong>${esc(x.name)}</strong><small>${esc(x.composition||'')}</small></span></label><div class="supp-dose"><input type="number" min="0" step="0.1" value="${x.dose??0}" data-item-dose="${x.id}" data-group="${id}"><span>${esc(x.unit||'')}</span></div></div>`).join('')||'<div class="empty-config">Sin elementos configurados.</div>'}
function renderRecordItems(){renderItemInputs(data.dailySupplements,'dailySupplements');renderItemInputs(data.sportSupplements,'sportSupplements');renderItemInputs(data.medications,'medications')}
function collectItems(group){const arr=data[group]||[];return arr.filter(x=>document.querySelector(`[data-item-check="${x.id}"][data-group="${group}"]`)?.checked).map(x=>({id:x.id,name:x.name,amount:Number(document.querySelector(`[data-item-dose="${x.id}"][data-group="${group}"]`)?.value||0),unit:x.unit,composition:x.composition||''}))}
function getNum(id){return $(id)?Number($(id).value||0):0}function getVal(id){return $(id)?$(id).value:''}
let editingDate=null;
function prepareNewRecord(){if(editingDate)return;$('entryDate').value=localISO();renderRecordItems();renderTrainingList()}
function resetForm(){editingDate=null;$('quickForm').reset();$('entryDate').value=localISO();document.querySelectorAll('#quickForm input[type=range]').forEach(r=>{r.value=0;r.dispatchEvent(new Event('input'))});$('usualSchedule').checked=true;$('usualFood').checked=true;$('sleepException').classList.add('hidden');$('foodException').classList.add('hidden');trainingDrafts=[];renderTrainingList();renderRecordItems()}
$('quickForm').onsubmit=e=>{e.preventDefault();syncTrainingDrafts();const date=$('entryDate').value||localISO();const sleepMinutes=parseDuration(getVal('sleepDuration'));if(getVal('sleepDuration')&&sleepMinutes===null)return alert('La duración del sueño debe ser minutos o h:mm, por ejemplo 455 o 07:35.');$('sleepDuration').value=minutesText(sleepMinutes||0);for(const [i,t] of trainingDrafts.entries()){const mins=parseDuration(t.duration);if(t.duration&&mins===null)return alert(`La duración del entrenamiento ${i+1} debe ser minutos o h:mm.`);t.durationMinutes=mins||0;t.duration=minutesText(mins||0);delete t.uid}
 const entry={id:`entry-${date}`,date,updatedAt:new Date().toISOString(),fatigue:getNum('fatigue'),legFatigue:$('legFatigue').checked,handSwelling:getNum('handSwelling'),handPain:getNum('handPain'),stress:getNum('stress'),eyeTic:$('eyeTic').checked,peeling:getNum('peeling'),calfTension:$('calfTension').checked,jawTension:$('jawTension').checked,sleepQuality:getNum('sleepQuality'),sleepDuration:minutesText(sleepMinutes||0),sleepMinutes:sleepMinutes||0,usualSchedule:$('usualSchedule').checked,sleepNotes:$('usualSchedule').checked?'':getVal('sleepNotes').trim(),usualFood:$('usualFood').checked,foodChange:$('usualFood').checked?'':getVal('foodChange'),foodNotes:$('usualFood').checked?'':getVal('foodNotes').trim(),trainings:clone(trainingDrafts),dailySupplements:collectItems('dailySupplements'),sportSupplements:collectItems('sportSupplements'),medicationsTaken:collectItems('medications'),notes:getVal('notes').trim()};
 const idx=data.entries.findIndex(x=>x.date===date);if(idx>=0&&!confirm(`Ya existe un registro del ${fmtDate(date)}. ¿Quieres actualizar exclusivamente ese día?`))return;if(idx>=0){entry.createdAt=data.entries[idx].createdAt||entry.updatedAt;data.entries[idx]=entry}else{entry.createdAt=entry.updatedAt;data.entries.push(entry)}data.entries.sort((a,b)=>a.date.localeCompare(b.date));saveData();const check=data.entries.find(x=>x.date===date);if(!check||check.date!==date)return alert('No se pudo verificar el guardado. Exporta la copia y no cierres la aplicación.');alert(`Registro del ${fmtDate(date)} guardado correctamente.`);resetForm();go('home');updateHome()};
function updateHome(){const e=data.entries.find(x=>x.date===localISO());const cards=document.querySelectorAll('.metric-card strong');if(cards[0])cards[0].textContent=e?e.handSwelling:0;if(cards[1])cards[1].textContent=e?e.fatigue:0;const pill=document.querySelector('.hero-card .pill');if(pill)pill.textContent=e?'Registro completado':'Registro pendiente'}updateHome();
let calendarDate=new Date();let selectedCalendarDate='';$('prevMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$('nextMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$('calendarTitle').textContent=new Intl.DateTimeFormat('es-ES',{month:'long',year:'numeric'}).format(calendarDate);const first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7,c=[];for(let i=0;i<start;i++)c.push('<div class="day empty"></div>');for(let d=1;d<=last.getDate();d++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,e=data.entries.find(x=>x.date===iso);let sev=0;if(e){const mx=Math.max(e.handSwelling||0,e.handPain||0,e.fatigue||0,e.legFatigue||0);sev=mx>=7?3:mx>=4?2:1}c.push(`<button class="day ${e?'has-entry severity-'+sev:''}${iso===localISO()?' today':''}${iso===selectedCalendarDate?' selected':''}" data-date="${iso}">${d}${e?'<span class="day-dot"></span>':''}</button>`)}$('calendarGrid').innerHTML=c.join('');document.querySelectorAll('.day[data-date]').forEach(b=>b.onclick=()=>{selectedCalendarDate=b.dataset.date;renderCalendar();showDay(b.dataset.date)})}
function trainingSummary(t){return `<div class="training-summary"><b>${esc(t.typeName||'Entrenamiento')}${t.competition?' · 🏁 Competición':''}</b><span>${t.duration||minutesText(t.durationMinutes||0)}${t.distanceKm?` · ${t.distanceKm} km`:''}${t.elevGain?` · +${t.elevGain} m`:''}${t.elevLoss?` · −${t.elevLoss} m`:''}${t.tssValue?` · ${t.tssValue} ${esc(t.tssType||'hrTSS')}`:''}${t.temperature?` · ${esc(t.temperature)}`:''}</span>${t.rpeGlobal!==undefined?`<span>RPE global ${t.rpeGlobal||0} · piernas ${t.rpeLegs||0} · cardio ${t.rpeCardio||0}</span>`:''}${t.notes?`<p>${esc(t.notes)}</p>`:''}</div>`}
function showDay(date){const e=data.entries.find(x=>x.date===date);if(!e){$('dayDetail').innerHTML=`<div class="day-detail-card"><strong>${fmtDate(date)}</strong><p class="muted">Sin registro.</p></div>`;return}const supp=[...(e.dailySupplements||[]),...(e.sportSupplements||[])];$('dayDetail').innerHTML=`<div class="day-detail-card"><strong>${fmtDate(date)}</strong><div class="detail-grid"><p><b>😴 Sueño:</b> ${e.sleepQuality??0}/100 · ${esc(e.sleepDuration||minutesText(e.sleepMinutes||0))}${e.usualSchedule===false?' · horario no habitual':''}</p><p><b>🤲 Salud:</b> inflamación ${e.handSwelling}/10 · dolor ${e.handPain}/10 · descamación ${e.peeling}/3</p><p><b>⚡ Estado:</b> cansancio ${e.fatigue}/10 · piernas cargadas ${e.legFatigue?'sí':'no'} · estrés ayer ${e.stress||0}/10${e.eyeTic?' · tic ocular':''}${e.calfTension?' · tensión gemelos':''}${e.jawTension?' · tensión mandibular':''}</p>${(e.trainings||[]).map(trainingSummary).join('')}${supp.length?`<p><b>💊 Suplementos:</b> ${supp.map(s=>`${esc(s.name)} ${s.amount} ${esc(s.unit)}`).join(' · ')}</p>`:''}${(e.medicationsTaken||[]).length?`<p><b>💉 Medicación:</b> ${e.medicationsTaken.map(s=>`${esc(s.name)} ${s.amount} ${esc(s.unit)}`).join(' · ')}</p>`:''}${e.usualFood===false?`<p><b>🍽️ Alimentación:</b> ${esc(e.foodChange)}${e.foodNotes?` · ${esc(e.foodNotes)}`:''}</p>`:''}${e.sleepNotes?`<p><b>Sueño:</b> ${esc(e.sleepNotes)}</p>`:''}${e.notes?`<p><b>Observaciones:</b> ${esc(e.notes)}</p>`:''}</div><div class="button-row"><button class="secondary-button" onclick="editEntry('${date}')">Editar</button><button class="danger" onclick="deleteEntry('${date}')">Eliminar</button></div></div>`}
window.deleteEntry=date=>{if(confirm('¿Eliminar este registro?')){data.entries=data.entries.filter(x=>x.date!==date);saveData();renderCalendar();$('dayDetail').innerHTML='';updateHome()}};
window.editEntry=date=>{const e=data.entries.find(x=>x.date===date);if(!e)return;editingDate=date;go('record');$('entryDate').value=e.date;for(const id of ['fatigue','handSwelling','handPain','stress','peeling']){$(id).value=e[id]||0;$(id).dispatchEvent(new Event('input'))}$('legFatigue').checked=!!e.legFatigue;$('eyeTic').checked=!!e.eyeTic;$('calfTension').checked=!!e.calfTension;$('jawTension').checked=!!e.jawTension;$('sleepQuality').value=e.sleepQuality||0;$('sleepDuration').value=e.sleepDuration||minutesText(e.sleepMinutes||0);$('usualSchedule').checked=e.usualSchedule!==false;$('sleepNotes').value=e.sleepNotes||'';$('sleepException').classList.toggle('hidden',$('usualSchedule').checked);$('usualFood').checked=e.usualFood!==false;$('foodChange').value=e.foodChange||'';$('foodNotes').value=e.foodNotes||'';$('foodException').classList.toggle('hidden',$('usualFood').checked);$('notes').value=e.notes||'';trainingDrafts=clone(e.trainings||[]).map((t,i)=>({...newTraining(),...t,uid:`edit-${i}`}));renderTrainingList();renderRecordItems();for(const group of ['dailySupplements','sportSupplements','medications']){const taken=group==='medications'?e.medicationsTaken||[]:e[group]||[];for(const x of taken){const cb=document.querySelector(`[data-item-check="${x.id}"][data-group="${group}"]`),dose=document.querySelector(`[data-item-dose="${x.id}"][data-group="${group}"]`);if(cb)cb.checked=true;if(dose)dose.value=x.amount}}};
function renderStats(){const arr=[...data.entries].sort((a,b)=>a.date.localeCompare(b.date));const avg=k=>arr.length?(arr.reduce((s,e)=>s+Number(e[k]||0),0)/arr.length).toFixed(1):'—';$('statsCards').innerHTML=[['Días registrados',arr.length],['Inflamación media',avg('handSwelling')],['Cansancio medio',avg('fatigue')],['Entrenamientos',arr.reduce((s,e)=>s+(e.trainings?.length||0),0)]].map(([l,v])=>`<article class="stat-card"><span>${l}</span><strong>${v}</strong></article>`).join('');drawChart(arr)}
function drawChart(arr){const c=$('statsChart'),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth||700,h=220;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#dfe8e8';for(let i=0;i<=5;i++){const y=20+i*(h-40)/5;ctx.beginPath();ctx.moveTo(28,y);ctx.lineTo(w-8,y);ctx.stroke()}if(!arr.length){ctx.fillStyle='#74868b';ctx.fillText('Sin datos',w/2-20,h/2);return}for(const [k,col] of [['handSwelling','#0f766e'],['fatigue','#d99a24']]){ctx.strokeStyle=col;ctx.lineWidth=3;ctx.beginPath();arr.forEach((e,i)=>{const x=30+i*(w-44)/Math.max(1,arr.length-1),y=h-20-(Number(e[k]||0)/10)*(h-40);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}}
const configMeta={dailySupplements:{title:'Suplemento diario'},sportSupplements:{title:'Suplemento deportivo'},medications:{title:'Medicación'},trainingTypes:{title:'Tipo de entrenamiento'}};
function renderSettings(){for(const key of ['dailySupplements','sportSupplements','medications','trainingTypes']){const list=$(key+'List'),arr=data[key]||[];list.innerHTML=arr.sort((a,b)=>(a.order||0)-(b.order||0)).map(x=>`<div class="config-item"><span class="config-grip">⋮⋮</span><div class="config-main"><strong>${esc(x.name)}</strong><small>${key==='trainingTypes'?esc(x.kind||'otro'):`${x.dose??0} ${esc(x.unit||'')} ${x.defaultTaken?'· marcado por defecto':''} ${x.composition?`· ${esc(x.composition)}`:''}`}</small></div><button class="config-toggle ${x.enabled!==false?'on':''}" data-toggle="${key}" data-id="${x.id}"></button><button class="icon-mini" data-edit="${key}" data-id="${x.id}">✎</button><button class="icon-mini danger-text" data-del="${key}" data-id="${x.id}">×</button></div>`).join('')||'<div class="empty-config">Sin elementos.</div>'}bindConfigButtons()}
function bindConfigButtons(){document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const x=data[b.dataset.toggle].find(v=>v.id===b.dataset.id);x.enabled=!x.enabled;saveData();renderSettings()});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openConfigModal(b.dataset.edit,b.dataset.id));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar este elemento?')){data[b.dataset.del]=data[b.dataset.del].filter(x=>x.id!==b.dataset.id);saveData();renderSettings()}})}
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openConfigModal(b.dataset.add));let modalState=null;
function openConfigModal(key,id=''){const item=id?data[key].find(x=>x.id===id):null;modalState={key,id};$('modalTitle').textContent=(item?'Editar ':'Añadir ')+(configMeta[key]?.title||'elemento');const isTrain=key==='trainingTypes';$('modalBody').innerHTML=`<label>Nombre<input id="cfgName" value="${esc(item?.name||'')}"></label>${isTrain?`<label>Tipo de formulario<select id="cfgKind"><option value="run">Carrera</option><option value="bike">Bici</option><option value="strength">Fuerza</option><option value="mobility">Movilidad</option><option value="trekking">Trekking</option><option value="other">Otros</option></select></label>`:`<div class="grid two"><label>Dosis habitual<input id="cfgDose" type="number" step="0.1" value="${item?.dose??0}"></label><label>Unidad<input id="cfgUnit" value="${esc(item?.unit||'')}"></label></div><label class="tick-card"><input id="cfgDefault" type="checkbox" ${item?.defaultTaken?'checked':''}><span>Marcado por defecto en Registro</span></label><label>Composición / detalle<textarea id="cfgComposition" rows="3">${esc(item?.composition||'')}</textarea></label>`}`;$('modalBackdrop').classList.add('open');if(isTrain&&item)$('cfgKind').value=item.kind||'other'}
$('modalCancel').onclick=()=>$('modalBackdrop').classList.remove('open');$('modalSave').onclick=()=>{const {key,id}=modalState,name=$('cfgName').value.trim();if(!name)return alert('Escribe un nombre.');let item=id?data[key].find(x=>x.id===id):null;if(!item){item={id:`${key}-${Date.now()}`,enabled:true,order:data[key].length+1};data[key].push(item)}item.name=name;if(key==='trainingTypes')item.kind=$('cfgKind').value;else{item.dose=Number($('cfgDose').value||0);item.unit=$('cfgUnit').value.trim();item.composition=$('cfgComposition').value.trim();item.defaultTaken=$('cfgDefault').checked}saveData();$('modalBackdrop').classList.remove('open');renderSettings()};
$('exportAll').onclick=()=>download(JSON.stringify(data,null,2),`healthlab_backup_${localISO()}.json`,'application/json');
$('exportCsv').onclick=()=>{const rows=[['date','sleepQuality','sleepDuration','fatigue','legFatigue','handSwelling','handPain','stress','eyeTic','calfTension','jawTension','peeling','trainings','dailySupplements','sportSupplements','medications','foodChange','notes']];for(const e of data.entries)rows.push([e.date,e.sleepQuality,e.sleepDuration,e.fatigue,e.legFatigue,e.handSwelling,e.handPain,e.stress,e.eyeTic,e.calfTension,e.jawTension,e.peeling,JSON.stringify(e.trainings||[]),JSON.stringify(e.dailySupplements||[]),JSON.stringify(e.sportSupplements||[]),JSON.stringify(e.medicationsTaken||[]),e.foodChange,e.notes]);const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');download(csv,`healthlab_${localISO()}.csv`,'text/csv;charset=utf-8')};
function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('importAll').onchange=async e=>{try{const obj=JSON.parse(await e.target.files[0].text());if(!obj||!Array.isArray(obj.entries))throw 0;if(confirm('Esto sustituirá todos los datos actuales. ¿Continuar?')){data=migrate(obj);saveData();alert('Datos importados.');renderSettings();updateHome()}}catch{alert('Archivo JSON no válido.')}};
$('resetDemo').onclick=()=>{if(confirm('¿Restablecer toda la aplicación?')){data=clone(defaults);saveData();location.reload()}};
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js?v=1.0.3');resetForm();renderSettings();
